<a href="https://colab.research.google.com/github/vaibhav0726/Ml-learning/blob/main/Vaibhav_Lab1Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

**Class Work**

In [ ]:
a = np.array(["string","integer","mradul","raghav"])

In [ ]:
print(a)

['string' 'ram' 'mradul' 'raghav']


In [ ]:
my_list = [[10.30,20,30,40],[50,60,70,80]]

In [ ]:
# a = np.array(my_list)

In [ ]:
print(a)  # printing a 
print(type(a))  # class name in numpy
print(a.shape)  # shape of list(m*n)
print(a.dtype)  # data type
print(a.size) # total number of elements
print(a.ndim) # number of dimensions

['string' 'ram' 'mradul' 'raghav']
<class 'numpy.ndarray'>
(4,)
<U6
4
1


**Assignment-1**

1. Numpy Creating Arrays

In [ ]:
import numpy as np
arr = np.array([10,20,30,40])
print(type(arr))

<class 'numpy.ndarray'>


2. Numpy Array Indexing

In [ ]:
print(arr[3])
print(arr[4])
print(arr[-1])

40
[20 30]


IndexError: ignored

3. Numpy Array Slicing

In [ ]:
arr = np.array([10,20,30,40,50,60,70,80,90,100])
print(arr[1:5:2]) # not including 5
print(arr[-4:-1])
print(arr[::-2]) # starting to end with reverse

[20 40]
[70 80 90]
[100  80  60  40  20]


4. Numpy DataTypes

In [ ]:
arr = np.array([10,20,30,40,50])
print(arr.dtype)
arr = np.array([1.2,2.3,3.4])
print(arr.dtype)
arr = np.array(["naman", "mradul", "vaibhav"])
print(arr.dtype)

int64
float64
<U7


5. Numpy copy

In [ ]:
arr = np.array([10,20,30,40,50])
temp = arr.copy()
arr[0] = 10
print(arr)
print(temp)

[42 20 30 40 50]
[10 20 30 40 50]


6. Numpy View

In [ ]:
arr = np.array([10,20,30,40,50])
temp = arr.view()
arr[0] = 90
print(arr)
print(temp)

[90 20 30 40 50]
[90 20 30 40 50]


7.  Numpy Array Shape

In [ ]:
newArr = [[10,20,30], [40,50,60], [70,80,90]]
arr = np.array(newArr)
print(arr)
print(arr.shape)

[[10 20 30]
 [40 50 60]
 [70 80 90]]
(3, 3)


8. Numpy Array Reshape

In [ ]:
arr = np.array([10,20,30,40,50,60,70,80,90,100,110,120])
newArr = arr.reshape(3,4)
print(newArr)

[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]


9. Numpy Array Iterating

In [ ]:
arr = np.array([10,20,30])
for i in arr:
  print(i)


10
20
30


10. Numpy Array Join 

In [ ]:
arr1 = np.array([10,20,30])
arr2 = np.array([40,50,60])
arr3 = np.concatenate( ( arr1, arr2 ) )
print( arr3 )

[10 20 30 40 50 60]


11. Numpy Array Split 

In [ ]:
arr = np.array([10,20,30,40,50,60,70,80,90,100])
arr2 = np.array_split(arr,3)
print(arr2)

[array([10, 20, 30, 40]), array([50, 60, 70]), array([ 80,  90, 100])]


12. Numpy Array Search

In [ ]:
arr = np.array([10,20,30,40,50])
temp = np.where(arr == 40)
print(temp) # prints index

(array([3]),)


13. Numpy Array Sort 

In [ ]:
arr = np.array([10,30,50,20,15])
print(np.sort(arr))


[10 15 20 30 50]


14. Numpy Array Filter 

In [ ]:
arr = np.array([10,20,30,40,50])
arr2 = [True, False, False, True, True]
arr3 = arr[temp]
print(arr3)

[40]
